[build]
  publish = "."

[[redirects]]
  from = "/car-registration"
  to = "/car-registration/index.html"
  status = 200

[[redirects]]
  from = "/car-registration/"
  to = "/car-registration/index.html"
  status = 200
